### ISSUE TITLE
请问支持隔空投送吗？还有如何进入引导界面

### ISSUE THREAD

**Issue by Lzirui** [FuckDoctors/ideapad-720s-13ikb-oc#1]
如题
现在会直接进入系统，不能选择进入恢复模式。
向您请教，谢谢。

**Comment by FuckDoctors** [comment]
支持隔空投送。
我用rEFInd引导的，里面隐藏恢复模式了。
https://github.com/FuckDoctors/ideapad-720s-13ikb-oc/blob/502b22d40886155b0992fea270500f247c4d3c07/EFI/refind/refind.conf#L7

**Comment by Lzirui** [comment]
好的，了解。
用rEFInd引导的话我这边是不是要重新配置。我是用的单系统，没有win。
还有就是连接移动设备没有反应，是驱动问题吗。
谢谢。

**Comment by FuckDoctors** [comment]
不用refind也可以。
你配置下oc就行了，按readme里的说明，改下showpicker，去掉oc的隐藏。

**Comment by Lzirui** [comment]
好的，谢谢
