### ISSUE TITLE
请问为什么把启动盘中的oc文件换成您的，引导界面选择install后会报错。

### ISSUE THREAD

**Issue by Lzirui** [FuckDoctors/ideapad-720s-13ikb-oc#2]
提示
OCB:system has no boot entries
OC:Failed to show boot menu!
Halting on critical error 
谢谢

**Comment by Lzirui** [comment]
查到的解决方案为
磁盘启动项扫描策略的问题，Misc~其他设置：-> Security -> ScanPolicy ->0：0表示允许扫描所有可用的硬盘
但是是不是要在mac系统上操作。

**Comment by FuckDoctors** [comment]
> 查到的解决方案为
> 磁盘启动项扫描策略的问题，Misc~其他设置：-> Security -> ScanPolicy ->0：0表示允许扫描所有可用的硬盘
> 但是是不是要在mac系统上操作。

这个是OC的配置，在config.plist中设置。

**Comment by Lzirui** [comment]
那么问题来了人，我没安装成冰就不能改，不能改就不能安装成功

**Comment by FuckDoctors** [comment]
这时OC引导的配置，安装前就能改啊
1. 确认BIOS配置是否正确
2. 确认下你的BOOT文件夹是否正确

**Comment by Lzirui** [comment]
不是要装occ才能改吗
我用我朋友的白苹果改了，现在问题来了
oc引导 install ，代码界面结束，又会回到oc引导界面

**Comment by Lzirui** [comment]
头疼

**Comment by FuckDoctors** [comment]
> 不是要装occ才能改吗
> 我用我朋友的白苹果改了，现在问题来了
> oc引导 install ，代码界面结束，又会回到oc引导界面

occ版本不一致容易出问题，所以，我都是用普通文本编辑器改的。
所以，安装前就可以修改。

**Comment by Lzirui** [comment]
好的 我研究研究 谢谢
