### ISSUE TITLE
你好 是不是不支持随航

### ISSUE THREAD

**Issue by Lzirui** [FuckDoctors/ideapad-720s-13ikb-oc#3]
iMessage也连不上，你的能连上吗

**Comment by FuckDoctors** [comment]
没弄iMessage，老的iPad也不支持随航，所以也没弄。

很久之前在台式机上折腾过iMessage，无果，最后台式机上注入了3码，iMessage, FaceTime都没问题了。
不需要iMessage所以没再折腾。
最有效的方式就是注入3码。

**Comment by Lzirui** [comment]
我注入了生成的三码没办法用，是需要白苹果的三码吗？如果注入白苹果三码，那白苹果还能用吗？

**Comment by FuckDoctors** [comment]
需要白苹果的三码，白苹果仍然可以用。
别太多人使用就行，你可以搜下相关说明。

**Comment by Lzirui** [comment]
ok 解决了。搞了朋友的序列号然后找的客服
