### ISSUE TITLE
成功升级big sur

### ISSUE THREAD

**Issue by Lzirui** [FuckDoctors/ideapad-720s-13ikb-oc#5]
大佬我根据你的EFI，然后用occ重新配置了一遍，ota成功升级。
https://wws.lanzous.com/i2evEflejaj
密码:fg9k
这是EFI

**Comment by FuckDoctors** [comment]
👍 我也就周末用用电脑，更新不频繁，你可以多折腾折腾

**Comment by Lzirui** [comment]
重启后禁行了，已经找到相应解决办法了，但是我也在备考中，也没有很多时间搞这个，等下次解决。
