### ISSUE TITLE
触控板没有反应不知道是怎么回事

### ISSUE THREAD

**Issue by LC95** [FuckDoctors/ideapad-720s-13ikb-oc#6]
我把原来的CLover的EFI删除,然后换上你的EFI文件.
系统能够正常启动, 什么都挺正常的除了触控板不能用
您知道怎么解决吗

**Comment by FuckDoctors** [comment]
重建缓存，重启下看看。
如果不行，就要看看触控板型号，定制SSDT了。

**Comment by LC95** [comment]
重建缓存重启也不行, 按理说两个电脑应该一样
