### ISSUE TITLE
大佬，我卡在SMCspuer IO 是为什么呢

### ISSUE THREAD

**Issue by livryti** [FuckDoctors/ideapad-720s-13ikb-oc#8]
我的机型是YOGA S730，我之前用你的EFI 是可以用的，在升级11的时候就卡在装系统的SPUERIO了。
SMCSuperIO ssio: starting up superIO sensors

**Comment by FuckDoctors** [comment]
我倒是没遇到，config.plist是正常的吗？
你看看远景的这个帖子：http://bbs.pcbeta.com/viewthread-1873746-1-1.html

**Comment by livryti** [comment]
好的，我再去折腾折腾，不早了，大佬早点休息，hhh，头发重要
